/**
 * qraReviewEngine.js — Question Review & Analysis Experience (QRA)
 * Mentorix Phase 12 — Exam-Focused, Fast, Distraction-Free Attempt Review
 *
 * Responsibilities:
 * - Question review & answer comparison (Student vs Correct)
 * - Official explanation rendering & KaTeX math pre-rendering
 * - Time spent, difficulty, chapter, and exam source metadata display
 * - Action controls: Bookmark (🔖), Retry Later (🔄), Report Issue (🚩), Ask Tio (✨)
 * - Student reflection tagging (Reason missed: Concept, Calculation, Misread, Time, Silly)
 * - Zero score recalculations, zero attempt history mutation
 */

'use strict';

(function () {
  let activeReviewState = null;

  const QRAReviewEngine = {
    /**
     * Open full-screen QRA Review Experience
     * @param {Object} evaluationReport — Report generated by Evaluation Engine (ESAI)
     * @param {Object} attemptPackage — Attempt package containing user responses & time
     * @param {Array} questionsList — List of question objects from session
     */
    openReview(evaluationReport, attemptPackage, questionsList) {
      if (!evaluationReport || !attemptPackage) {
        console.error('[QRAReviewEngine] Cannot open review: Missing evaluation report or attempt package.');
        if (typeof toast === 'function') toast('Unable to load review data', 'err');
        return;
      }

      const questions = questionsList || attemptPackage.questions || [];
      if (!questions.length) {
        if (typeof toast === 'function') toast('No questions available for review', 'warn');
        return;
      }

      // Initialize review state
      activeReviewState = {
        evaluationReport,
        attemptPackage,
        questions,
        currentIndex: 0,
        total: questions.length,
        reflections: {},
        filter: 'all' // 'all', 'incorrect', 'correct', 'skipped', 'bookmarked'
      };

      this.renderOverlay();
      this.renderQuestionCard();

      // Trigger KaTeX rendering on opening
      if (typeof window.renderMath === 'function') {
        setTimeout(() => window.renderMath(document.getElementById('qra-card-body')), 80);
      }
    },

    /**
     * Render main full-screen QRA Review Overlay
     */
    renderOverlay() {
      const old = document.getElementById('qra-review-overlay');
      if (old) old.remove();

      const overlay = document.createElement('div');
      overlay.id = 'qra-review-overlay';
      overlay.className = 'qra-overlay';
      overlay.style.cssText = `
        position: fixed;
        top: 0; left: 0; width: 100vw; height: 100vh;
        background: var(--bg, #0a0a0f);
        z-index: 99999;
        display: flex;
        flex-direction: column;
        overflow: hidden;
        color: #fff;
        font-family: var(--f-body, 'Inter', sans-serif);
      `;

      const ev = activeReviewState.evaluationReport;
      const att = activeReviewState.attemptPackage;

      overlay.innerHTML = `
        <!-- Top Navigation Header -->
        <div class="qra-header" style="padding:14px 20px;background:rgba(18,18,26,0.95);border-bottom:1px solid var(--brd,rgba(255,255,255,0.08));display:flex;align-items:center;justify-content:space-between;gap:12px;backdrop-filter:blur(12px)">
          <div style="display:flex;align-items:center;gap:12px">
            <button class="btn bgh bsm" onclick="QRAReviewEngine.closeReview()" style="padding:6px 14px;font-size:13px">← Close Review</button>
            <div>
              <div style="font-family:var(--f-display,'Space Grotesk');font-weight:700;font-size:15px;color:#fff">
                ${esc(ev.exam || att.exam || 'Exam')} Review & Analysis
              </div>
              <div style="font-size:11px;color:var(--mut,#475569)">
                Score: <strong style="color:var(--pl,#a78bfa)">${ev.totalScore}</strong> · Accuracy: <strong>${ev.accuracyPct}%</strong> (${ev.correctCount}/${ev.totalQuestions})
              </div>
            </div>
          </div>

          <!-- Filter Pills -->
          <div style="display:flex;align-items:center;gap:6px;overflow-x:auto;padding:2px">
            <button class="qra-filter-btn active" id="qra-flt-all" onclick="QRAReviewEngine.setFilter('all')">All (${ev.totalQuestions})</button>
            <button class="qra-filter-btn" id="qra-flt-incorrect" onclick="QRAReviewEngine.setFilter('incorrect')" style="color:var(--redl,#ef4444)">Incorrect (${ev.incorrectCount})</button>
            <button class="qra-filter-btn" id="qra-flt-correct" onclick="QRAReviewEngine.setFilter('correct')" style="color:var(--okl,#10b981)">Correct (${ev.correctCount})</button>
            <button class="qra-filter-btn" id="qra-flt-skipped" onclick="QRAReviewEngine.setFilter('skipped')" style="color:var(--goldl,#f59e0b)">Skipped (${ev.unattemptedCount})</button>
          </div>
        </div>

        <!-- Main Body: Split Sidebar Palette + Card -->
        <div style="flex:1;display:flex;overflow:hidden">
          <!-- Left Question Palette Sidebar -->
          <div class="qra-sidebar" style="width:240px;background:rgba(18,18,26,0.6);border-right:1px solid var(--brd,rgba(255,255,255,0.08));padding:16px;display:flex;flex-direction:column;gap:12px;overflow-y:auto">
            <div style="font-size:11px;font-weight:700;color:var(--mut,#475569);letter-spacing:.5px;text-transform:uppercase">Question Palette</div>
            <div id="qra-palette-grid" style="display:grid;grid-template-columns:repeat(5,1fr);gap:6px">
              ${this.buildPaletteGridHTML()}
            </div>

            <!-- Quick Stats Card -->
            <div class="card" style="margin-top:auto;padding:12px;background:rgba(255,255,255,0.02);font-size:11px;color:var(--sub,#94a3b8)">
              <div style="font-weight:700;color:#fff;margin-bottom:4px">💡 Exam Tip</div>
              Review your incorrect answers first to identify concept gaps before re-attempting!
            </div>
          </div>

          <!-- Right Review Card Container -->
          <div style="flex:1;display:flex;flex-direction:column;overflow-y:auto;padding:24px" id="qra-card-container">
            <div id="qra-card-body" style="max-width:860px;margin:0 auto;width:100%"></div>
          </div>
        </div>

        <!-- Bottom Action Bar -->
        <div style="padding:12px 24px;background:rgba(18,18,26,0.95);border-top:1px solid var(--brd,rgba(255,255,255,0.08));display:flex;align-items:center;justify-content:space-between">
          <button class="btn bgh" id="qra-btn-prev" onclick="QRAReviewEngine.navigate(-1)">← Previous</button>
          <span id="qra-card-counter" style="font-size:13px;color:var(--sub,#94a3b8)">Question 1 of ${ev.totalQuestions}</span>
          <button class="btn bpri" id="qra-btn-next" onclick="QRAReviewEngine.navigate(1)">Next →</button>
        </div>
      `;

      document.body.appendChild(overlay);
    },

    /**
     * Build HTML for left Question Palette Grid
     */
    buildPaletteGridHTML() {
      if (!activeReviewState) return '';
      const ev = activeReviewState.evaluationReport;
      const items = ev.itemEvaluations || [];

      return activeReviewState.questions.map((q, idx) => {
        const evalItem = items[idx] || {};
        const status = evalItem.status || 'unattempted';
        const isCurrent = idx === activeReviewState.currentIndex;

        let bg = 'rgba(255,255,255,0.05)';
        let color = '#fff';
        let border = '1px solid var(--brd,rgba(255,255,255,0.1))';

        if (status === 'correct') {
          bg = 'rgba(16,185,129,0.15)';
          color = 'var(--okl,#10b981)';
          border = '1px solid rgba(16,185,129,0.4)';
        } else if (status === 'incorrect') {
          bg = 'rgba(239,68,68,0.15)';
          color = 'var(--redl,#ef4444)';
          border = '1px solid rgba(239,68,68,0.4)';
        } else if (status === 'unattempted') {
          bg = 'rgba(245,158,11,0.15)';
          color = 'var(--goldl,#f59e0b)';
          border = '1px solid rgba(245,158,11,0.4)';
        }

        if (isCurrent) {
          border = '2px solid var(--p,#8b5cf6)';
          bg = 'rgba(139,92,246,0.25)';
        }

        return `
          <button onclick="QRAReviewEngine.goToQuestion(${idx})" style="aspect-ratio:1;border-radius:8px;background:${bg};color:${color};border:${border};font-weight:700;font-size:12px;cursor:pointer;transition:all .15s">
            ${idx + 1}
          </button>
        `;
      }).join('');
    },

    /**
     * Render Question Card for current index
     */
    renderQuestionCard() {
      if (!activeReviewState) return;
      const container = document.getElementById('qra-card-body');
      if (!container) return;

      const idx = activeReviewState.currentIndex;
      const q = activeReviewState.questions[idx];
      const ev = activeReviewState.evaluationReport;
      const att = activeReviewState.attemptPackage;
      const evalItem = (ev.itemEvaluations || [])[idx] || {};

      const userAns = evalItem.userAnswer !== undefined ? evalItem.userAnswer : (att.responses ? att.responses[idx] : undefined);
      const status = evalItem.status || 'unattempted';

      // Metadata formats
      const isBookmarked = !!(D.memory?.bookmarks && D.memory.bookmarks[q.id || `q_${idx}`]);
      const isInRetry = !!(D.memory?.retryQueue && D.memory.retryQueue.includes(q.id || `q_${idx}`));
      const reflection = D.memory?.reflections ? D.memory.reflections[q.id || `q_${idx}`] : null;

      let statusBadge = '<span class="tag gold">Skipped</span>';
      if (status === 'correct') statusBadge = '<span class="tag ok">✅ Correct (+4)</span>';
      else if (status === 'incorrect') statusBadge = '<span class="tag red">❌ Incorrect (-1)</span>';

      const examSource = q.paper || q.examSource || ev.exam || 'Official Exam';
      const chapter = q.chapter || q.topic || 'General Physics';
      const difficulty = q.difficulty || 'Medium';

      // Process image HTML if question contains image
      let imageHTML = '';
      if (q.hasImage || q.imagePath || q.img) {
        const imgSrc = q.imagePath || q.img;
        imageHTML = `<div style="margin:14px 0"><img src="${esc(imgSrc)}" style="max-width:100%;max-height:300px;border-radius:10px;border:1px solid var(--brd,rgba(255,255,255,0.1))" alt="Question Diagram" /></div>`;
      }

      container.innerHTML = `
        <div class="card" style="padding:24px;background:var(--surface,#12121a);border:1px solid var(--brd,rgba(255,255,255,0.08));border-radius:16px;box-shadow:0 8px 32px rgba(0,0,0,0.4)">
          <!-- Top Card Meta Row -->
          <div style="display:flex;align-items:center;justify-content:space-between;flex-wrap:wrap;gap:8px;margin-bottom:16px;padding-bottom:12px;border-bottom:1px solid var(--brd,rgba(255,255,255,0.08))">
            <div style="display:flex;align-items:center;gap:8px;flex-wrap:wrap">
              ${statusBadge}
              <span class="tag" style="background:rgba(255,255,255,0.05);color:var(--sub,#94a3b8);font-size:11px">📍 ${esc(examSource)}</span>
              <span class="tag" style="background:rgba(139,92,246,0.1);color:var(--pl,#a78bfa);font-size:11px">📚 ${esc(chapter)}</span>
              <span class="tag" style="background:rgba(6,182,212,0.1);color:var(--cl,#22d3ee);font-size:11px">⚡ ${esc(difficulty)}</span>
            </div>

            <!-- Action Controls -->
            <div style="display:flex;align-items:center;gap:6px">
              <button class="btn bgh bsm" onclick="QRAReviewEngine.toggleBookmark('${q.id || `q_${idx}`}')" style="font-size:12px;padding:4px 10px">
                ${isBookmarked ? '🔖 Bookmarked' : '🔖 Bookmark'}
              </button>
              <button class="btn bgh bsm" onclick="QRAReviewEngine.toggleRetry('${q.id || `q_${idx}`}')" style="font-size:12px;padding:4px 10px">
                ${isInRetry ? '🔄 In Retry Queue' : '🔄 Retry Later'}
              </button>
              <button class="btn bgh bsm" onclick="QRAReviewEngine.openReportModal('${q.id || `q_${idx}`}')" style="font-size:12px;padding:4px 10px;color:var(--redl,#ef4444)">
                🚩 Report Issue
              </button>
            </div>
          </div>

          <!-- Question Body -->
          <div style="font-size:16px;line-height:1.6;color:#fff;margin-bottom:18px">
            <strong style="color:var(--pl,#a78bfa)">Q${idx + 1}.</strong> ${esc(q.q || q.question || 'Question content')}
          </div>
          ${imageHTML}

          <!-- Answer Comparison Grid -->
          <div style="display:grid;grid-template-columns:1fr 1fr;gap:12px;margin:20px 0;padding:16px;background:rgba(0,0,0,0.2);border-radius:12px;border:1px solid var(--brd,rgba(255,255,255,0.06))">
            <div>
              <div style="font-size:11px;font-weight:700;color:var(--mut,#475569);letter-spacing:.5px;text-transform:uppercase;margin-bottom:6px">YOUR ANSWER</div>
              <div style="font-size:14px;font-weight:700;color:${status === 'correct' ? 'var(--okl,#10b981)' : status === 'incorrect' ? 'var(--redl,#ef4444)' : 'var(--goldl,#f59e0b)'}">
                ${this.formatAnswerDisplay(userAns, q)}
              </div>
            </div>
            <div>
              <div style="font-size:11px;font-weight:700;color:var(--mut,#475569);letter-spacing:.5px;text-transform:uppercase;margin-bottom:6px">CORRECT ANSWER</div>
              <div style="font-size:14px;font-weight:700;color:var(--okl,#10b981)">
                ${this.formatAnswerDisplay(q.ans || q.correct, q)}
              </div>
            </div>
          </div>

          <!-- Official Explanation Section -->
          <div style="margin-top:20px;padding:16px;background:rgba(139,92,246,0.05);border:1px solid rgba(139,92,246,0.2);border-radius:12px">
            <div style="display:flex;align-items:center;justify-content:space-between;margin-bottom:8px">
              <div style="font-size:12px;font-weight:700;color:var(--pl,#a78bfa);letter-spacing:.5px">💡 OFFICIAL EXPLANATION & SOLUTION</div>
              <button class="btn bsm bpri" onclick="QRAReviewEngine.askTioAboutQuestion(${idx})" style="font-size:11px;padding:3px 8px">✨ Ask Tio to Explain</button>
            </div>
            <div style="font-size:14px;line-height:1.6;color:var(--sub,#94a3b8)">
              ${esc(q.expl || q.explanation || 'Self-explanatory standard concept.')}
            </div>
          </div>

          <!-- Reflection Box for Incorrect Questions -->
          ${status === 'incorrect' ? `
            <div style="margin-top:20px;padding:14px;background:rgba(239,68,68,0.05);border:1px dashed rgba(239,68,68,0.3);border-radius:12px">
              <div style="font-size:12px;font-weight:700;color:var(--redl,#ef4444);margin-bottom:8px">🤔 STUDENT REFLECTION — What caused this mistake?</div>
              <div style="display:flex;gap:8px;flex-wrap:wrap">
                ${['Didn\'t know concept', 'Calculation mistake', 'Misread question', 'Time pressure', 'Silly mistake'].map(reason => `
                  <button class="btn bsm ${reflection === reason ? 'bpri' : 'bgh'}" onclick="QRAReviewEngine.saveReflection('${q.id || `q_${idx}`}', '${reason}')" style="font-size:11px;padding:4px 10px">
                    ${reflection === reason ? '✓ ' + reason : reason}
                  </button>
                `).join('')}
              </div>
            </div>
          ` : ''}
        </div>
      `;

      // Update palette grid current highlight & counter
      const paletteContainer = document.getElementById('qra-palette-grid');
      if (paletteContainer) paletteContainer.innerHTML = this.buildPaletteGridHTML();

      const counterEl = document.getElementById('qra-card-counter');
      if (counterEl) counterEl.textContent = `Question ${idx + 1} of ${activeReviewState.total}`;

      // Re-trigger KaTeX math rendering
      if (typeof window.renderMath === 'function') {
        setTimeout(() => window.renderMath(container), 50);
      }
    },

    /**
     * Format answer representation into human-readable string
     */
    formatAnswerDisplay(ans, q) {
      if (ans === undefined || ans === null || ans === '' || (Array.isArray(ans) && ans.length === 0)) {
        return '<em>Unattempted / Skipped</em>';
      }

      if (q.type === 'numerical') {
        return String(ans);
      }

      if (q.opts && q.opts.length > 0) {
        const arr = Array.isArray(ans) ? ans : [ans];
        return arr.map(a => `${String.fromCharCode(65 + Number(a))}: ${q.opts[a] || ''}`).join(' / ');
      }

      return Array.isArray(ans) ? ans.join(', ') : String(ans);
    },

    /**
     * Navigate between questions (-1 or +1)
     */
    navigate(direction) {
      if (!activeReviewState) return;
      let newIdx = activeReviewState.currentIndex + direction;
      if (newIdx < 0) newIdx = 0;
      if (newIdx >= activeReviewState.total) newIdx = activeReviewState.total - 1;

      activeReviewState.currentIndex = newIdx;
      this.renderQuestionCard();
    },

    /**
     * Jump directly to specific question index
     */
    goToQuestion(idx) {
      if (!activeReviewState) return;
      if (idx >= 0 && idx < activeReviewState.total) {
        activeReviewState.currentIndex = idx;
        this.renderQuestionCard();
      }
    },

    /**
     * Set Question Palette Filter ('all', 'incorrect', 'correct', 'skipped')
     */
    setFilter(filterType) {
      if (!activeReviewState) return;
      activeReviewState.filter = filterType;

      document.querySelectorAll('.qra-filter-btn').forEach(b => b.classList.remove('active'));
      const activeBtn = document.getElementById(`qra-flt-${filterType}`);
      if (activeBtn) activeBtn.classList.add('active');

      // Jump to first matching question of filter
      const items = activeReviewState.evaluationReport.itemEvaluations || [];
      const matchIdx = items.findIndex(item => {
        if (filterType === 'all') return true;
        if (filterType === 'incorrect') return item.status === 'incorrect';
        if (filterType === 'correct') return item.status === 'correct';
        if (filterType === 'skipped') return item.status === 'unattempted';
        return true;
      });

      if (matchIdx !== -1) {
        activeReviewState.currentIndex = matchIdx;
      }
      this.renderQuestionCard();
    },

    /**
     * Toggle Bookmark for Question ID
     */
    toggleBookmark(qId) {
      if (!window.D) return;
      if (!D.memory) D.memory = {};
      if (!D.memory.bookmarks) D.memory.bookmarks = {};

      if (D.memory.bookmarks[qId]) {
        delete D.memory.bookmarks[qId];
        if (typeof toast === 'function') toast('Bookmark removed', 'info');
      } else {
        D.memory.bookmarks[qId] = true;
        if (typeof toast === 'function') toast('Question bookmarked 🔖', 'ok2');
      }

      if (typeof window.saveAll === 'function') window.saveAll();
      this.renderQuestionCard();
    },

    /**
     * Toggle Retry Queue item
     */
    toggleRetry(qId) {
      if (!window.D) return;
      if (!D.memory) D.memory = {};
      if (!D.memory.retryQueue) D.memory.retryQueue = [];

      const idx = D.memory.retryQueue.indexOf(qId);
      if (idx !== -1) {
        D.memory.retryQueue.splice(idx, 1);
        if (typeof toast === 'function') toast('Removed from Retry Queue', 'info');
      } else {
        D.memory.retryQueue.push(qId);
        if (typeof toast === 'function') toast('Added to Retry Queue 🔄', 'ok2');
      }

      if (typeof window.saveAll === 'function') window.saveAll();
      this.renderQuestionCard();
    },

    /**
     * Save Student Reflection Tag
     */
    saveReflection(qId, reason) {
      if (!window.D) return;
      if (!D.memory) D.memory = {};
      if (!D.memory.reflections) D.memory.reflections = {};

      D.memory.reflections[qId] = reason;
      if (typeof window.saveAll === 'function') window.saveAll();
      if (typeof toast === 'function') toast(`Reflection saved: "${reason}"`, 'ok2');
      this.renderQuestionCard();
    },

    /**
     * Open Report Issue Modal
     */
    openReportModal(qId) {
      const modal = document.createElement('div');
      modal.className = 'confirm-modal-bg';
      modal.style.zIndex = '100005';
      modal.innerHTML = `
        <div class="confirm-modal" style="max-width:420px;text-align:left">
          <div class="confirm-modal-title" style="color:var(--redl,#ef4444)">🚩 Report Question Issue</div>
          <div class="confirm-modal-msg" style="margin-bottom:14px">Select the issue with question ID <code>${qId}</code>:</div>
          <div style="display:flex;flex-direction:column;gap:8px;margin-bottom:16px">
            <label style="display:flex;align-items:center;gap:8px;font-size:13px;cursor:pointer"><input type="radio" name="qra-report-type" value="Wrong Answer" checked /> Wrong Answer / Solution</label>
            <label style="display:flex;align-items:center;gap:8px;font-size:13px;cursor:pointer"><input type="radio" name="qra-report-type" value="Broken KaTeX" /> Broken KaTeX / Math formatting</label>
            <label style="display:flex;align-items:center;gap:8px;font-size:13px;cursor:pointer"><input type="radio" name="qra-report-type" value="Incorrect Classification" /> Incorrect Chapter / Topic</label>
            <label style="display:flex;align-items:center;gap:8px;font-size:13px;cursor:pointer"><input type="radio" name="qra-report-type" value="Missing Image" /> Missing Image / Diagram</label>
            <label style="display:flex;align-items:center;gap:8px;font-size:13px;cursor:pointer"><input type="radio" name="qra-report-type" value="Typo" /> Typo / Grammatical error</label>
          </div>
          <div class="confirm-modal-btns">
            <button class="btn bgh" onclick="this.closest('.confirm-modal-bg').remove()">Cancel</button>
            <button class="btn bpri" onclick="QRAReviewEngine.submitReport('${qId}', this)">Submit Report</button>
          </div>
        </div>
      `;
      document.body.appendChild(modal);
    },

    /**
     * Submit Question Report
     */
    submitReport(qId, btnEl) {
      const modalBg = btnEl.closest('.confirm-modal-bg');
      const selected = modalBg.querySelector('input[name="qra-report-type"]:checked');
      const reason = selected ? selected.value : 'General Issue';

      if (!window.D) return;
      if (!D.memory) D.memory = {};
      if (!D.memory.reportedIssues) D.memory.reportedIssues = [];

      D.memory.reportedIssues.push({
        questionId: qId,
        reason,
        reportedAt: Date.now()
      });

      if (typeof window.saveAll === 'function') window.saveAll();
      if (typeof toast === 'function') toast(`Report submitted for ${qId}`, 'ok2');
      modalBg.remove();
    },

    /**
     * Open Tio Conversation pre-loaded with Question Context
     */
    askTioAboutQuestion(idx) {
      if (!activeReviewState) return;
      const q = activeReviewState.questions[idx];
      const promptText = `Can you explain Question ${idx + 1} from ${q.chapter || 'my exam'} in a clear step-by-step way?\n\nQuestion: ${q.q || q.question}\nCorrect Answer: ${q.ans || q.correct}\nExplanation: ${q.expl || 'None'}`;

      if (typeof window.openTioFloat === 'function') {
        window.openTioFloat(promptText);
      } else if (typeof toast === 'function') {
        toast('Tio AI context updated', 'ok2');
      }
    },

    /**
     * Close QRA Review Overlay
     */
    closeReview() {
      const overlay = document.getElementById('qra-review-overlay');
      if (overlay) overlay.remove();
      activeReviewState = null;
    }
  };

  /* ── EXPORTS TO WINDOW ────────────────────────────────────── */
  window.QRAReviewEngine = QRAReviewEngine;
})();
